In [9]:
import pandas as pd
import glob
import os

# 1. Get file list
path = 'path_to_csv_files'
all_files = glob.glob(os.path.join("HUPA*.csv"))

# 2. & 3. Read, add columns, and append to list
li = []
for filename in all_files:
    df = pd.read_csv(filename,sep=";")
    patientid = filename.split(".")[0]
    df['Patient_ID'] = os.path.basename(patientid) # Adding column
    li.append(df)

# Concatenate all into one DataFrame
df_final = pd.concat(li, ignore_index=True)

In [10]:
df_final

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID
0,2018-06-13T18:40:00,332.000000,6.35950,82.322835,34.0,0.091667,0.0,0.0,HUPA0001P
1,2018-06-13T18:45:00,326.000000,7.72800,83.740157,0.0,0.091667,0.0,0.0,HUPA0001P
2,2018-06-13T18:50:00,330.000000,4.74950,80.525180,0.0,0.091667,0.0,0.0,HUPA0001P
3,2018-06-13T18:55:00,324.000000,6.35950,89.129032,20.0,0.091667,0.0,0.0,HUPA0001P
4,2018-06-13T19:00:00,306.000000,5.15200,92.495652,0.0,0.075000,0.0,0.0,HUPA0001P
...,...,...,...,...,...,...,...,...,...
309387,2022-05-18T11:55:00,109.333333,10.79280,104.171171,0.0,0.000000,0.0,0.0,HUPA0028P
309388,2022-05-18T12:00:00,114.000000,9.80346,103.442623,0.0,0.000000,0.0,0.0,HUPA0028P
309389,2022-05-18T12:05:00,118.666667,5.66622,95.542857,0.0,0.000000,0.0,0.0,HUPA0028P
309390,2022-05-18T12:10:00,123.333333,5.57628,91.381356,0.0,0.000000,0.0,0.0,HUPA0028P
309391,2022-05-18T12:15:00,128.000000,5.57628,99.257812,0.0,0.000000,0.0,0.0,HUPA0028P

In [ ]:
df_final.to_excel("output.xlsx", index=False, sheet_name='DataSheet')

In [11]:
# Split by the space delimiter and expand into two columns
df_final[['Date', 'Time']] = df_final['time'].astype(str).str.split('T', expand=True)
df_final

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID,Date,Time
0,2018-06-13T18:40:00,332.000000,6.35950,82.322835,34.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:40:00
1,2018-06-13T18:45:00,326.000000,7.72800,83.740157,0.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:45:00
2,2018-06-13T18:50:00,330.000000,4.74950,80.525180,0.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:50:00
3,2018-06-13T18:55:00,324.000000,6.35950,89.129032,20.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:55:00
4,2018-06-13T19:00:00,306.000000,5.15200,92.495652,0.0,0.075000,0.0,0.0,HUPA0001P,2018-06-13,19:00:00
...,...,...,...,...,...,...,...,...,...,...,...
309387,2022-05-18T11:55:00,109.333333,10.79280,104.171171,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,11:55:00
309388,2022-05-18T12:00:00,114.000000,9.80346,103.442623,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:00:00
309389,2022-05-18T12:05:00,118.666667,5.66622,95.542857,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:05:00
309390,2022-05-18T12:10:00,123.333333,5.57628,91.381356,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:10:00
309391,2022-05-18T12:15:00,128.000000,5.57628,99.257812,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:15:00

In [12]:
# drop old datetime column
df = df_final.drop('time', axis=1)
df
if 'Patient_ID' in df:
    print("exists")

exists

In [14]:
df2 = pd.read_excel('T1DM_patient_sleep_demographics_with_race.xlsx')

# Join the files on the common 'Patient ID' column
# Use how='inner' to keep only matches, or how='left' to keep all from file1
merged_df = pd.merge(df, df2, on='Patient_ID', how='inner')

# Save the result to a new Excel file
merged_df.to_excel('merged_patients.xlsx', index=False)

In [15]:
df = merged_df.drop_duplicates()
df

,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID,Date,Time,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,332.000000,6.35950,82.322835,34.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:40:00,34,Male,Other,6.3,4.5,80
1,326.000000,7.72800,83.740157,0.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:45:00,34,Male,Other,6.3,4.5,80
2,330.000000,4.74950,80.525180,0.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:50:00,34,Male,Other,6.3,4.5,80
3,324.000000,6.35950,89.129032,20.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:55:00,34,Male,Other,6.3,4.5,80
4,306.000000,5.15200,92.495652,0.0,0.075000,0.0,0.0,HUPA0001P,2018-06-13,19:00:00,34,Male,Other,6.3,4.5,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309387,109.333333,10.79280,104.171171,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,11:55:00,62,Male,Black,5.1,7.9,30
309388,114.000000,9.80346,103.442623,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:00:00,62,Male,Black,5.1,7.9,30
309389,118.666667,5.66622,95.542857,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:05:00,62,Male,Black,5.1,7.9,30
309390,123.333333,5.57628,91.381356,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:10:00,62,Male,Black,5.1,7.9,30
309391,128.000000,5.57628,99.257812,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:15:00,62,Male,Black,5.1,7.9,30

In [16]:
merged_df.drop_duplicates()

,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID,Date,Time,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,332.000000,6.35950,82.322835,34.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:40:00,34,Male,Other,6.3,4.5,80
1,326.000000,7.72800,83.740157,0.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:45:00,34,Male,Other,6.3,4.5,80
2,330.000000,4.74950,80.525180,0.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:50:00,34,Male,Other,6.3,4.5,80
3,324.000000,6.35950,89.129032,20.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:55:00,34,Male,Other,6.3,4.5,80
4,306.000000,5.15200,92.495652,0.0,0.075000,0.0,0.0,HUPA0001P,2018-06-13,19:00:00,34,Male,Other,6.3,4.5,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309387,109.333333,10.79280,104.171171,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,11:55:00,62,Male,Black,5.1,7.9,30
309388,114.000000,9.80346,103.442623,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:00:00,62,Male,Black,5.1,7.9,30
309389,118.666667,5.66622,95.542857,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:05:00,62,Male,Black,5.1,7.9,30
309390,123.333333,5.57628,91.381356,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:10:00,62,Male,Black,5.1,7.9,30
309391,128.000000,5.57628,99.257812,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:15:00,62,Male,Black,5.1,7.9,30

In [17]:
df

,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID,Date,Time,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,332.000000,6.35950,82.322835,34.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:40:00,34,Male,Other,6.3,4.5,80
1,326.000000,7.72800,83.740157,0.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:45:00,34,Male,Other,6.3,4.5,80
2,330.000000,4.74950,80.525180,0.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:50:00,34,Male,Other,6.3,4.5,80
3,324.000000,6.35950,89.129032,20.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:55:00,34,Male,Other,6.3,4.5,80
4,306.000000,5.15200,92.495652,0.0,0.075000,0.0,0.0,HUPA0001P,2018-06-13,19:00:00,34,Male,Other,6.3,4.5,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309387,109.333333,10.79280,104.171171,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,11:55:00,62,Male,Black,5.1,7.9,30
309388,114.000000,9.80346,103.442623,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:00:00,62,Male,Black,5.1,7.9,30
309389,118.666667,5.66622,95.542857,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:05:00,62,Male,Black,5.1,7.9,30
309390,123.333333,5.57628,91.381356,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:10:00,62,Male,Black,5.1,7.9,30
309391,128.000000,5.57628,99.257812,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:15:00,62,Male,Black,5.1,7.9,30

In [18]:
df.isnull().values.any()

np.False_

In [19]:
df['glucose'].isnull().any()

np.False_

In [20]:
# Standardize column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df

,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id,date,time,age,gender,race,average_sleep_duration_(hrs),sleep_quality_(1-10),%_with_sleep_disturbances
0,332.000000,6.35950,82.322835,34.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:40:00,34,Male,Other,6.3,4.5,80
1,326.000000,7.72800,83.740157,0.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:45:00,34,Male,Other,6.3,4.5,80
2,330.000000,4.74950,80.525180,0.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:50:00,34,Male,Other,6.3,4.5,80
3,324.000000,6.35950,89.129032,20.0,0.091667,0.0,0.0,HUPA0001P,2018-06-13,18:55:00,34,Male,Other,6.3,4.5,80
4,306.000000,5.15200,92.495652,0.0,0.075000,0.0,0.0,HUPA0001P,2018-06-13,19:00:00,34,Male,Other,6.3,4.5,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309387,109.333333,10.79280,104.171171,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,11:55:00,62,Male,Black,5.1,7.9,30
309388,114.000000,9.80346,103.442623,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:00:00,62,Male,Black,5.1,7.9,30
309389,118.666667,5.66622,95.542857,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:05:00,62,Male,Black,5.1,7.9,30
309390,123.333333,5.57628,91.381356,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:10:00,62,Male,Black,5.1,7.9,30
309391,128.000000,5.57628,99.257812,0.0,0.000000,0.0,0.0,HUPA0028P,2022-05-18,12:15:00,62,Male,Black,5.1,7.9,30

In [22]:
df['%_with_sleep_disturbances']

0         80
1         80
2         80
3         80
4         80
          ..
309387    30
309388    30
309389    30
309390    30
309391    30
Name: %_with_sleep_disturbances, Length: 309392, dtype: int64

In [ ]:
#outliers : heart rate, glucose
#column change and bring to first
#ideal range for each column
#round off the decimal points, glucose

In [23]:
df.to_excel("cleaned_data.xlsx", index=False, sheet_name='DataSheet')